USE hbs
GO
/****** Object:  Table [dbo].[bandeja_alertas_generadas_SOS]    Script Date: 5/8/2025 15:14:35 ******/

IF OBJECT_ID('bandeja_alertas_generadas_SOS', 'U') IS NOT NULL 
	DROP TABLE [dbo].[bandeja_alertas_generadas_SOS]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[bandeja_alertas_generadas_SOS](
	[ID_ALERTA] [int] NOT NULL,
	[CODIGO_ALERTA] [varchar](50) NOT NULL,
	[CUIL] [varchar](30) NOT NULL,
	[SUCURSAL] [varchar](255) NOT NULL,
	[FECHA_ALTA_ALERTA] [datetime] NOT NULL,
	[FECHA_VTO_ALERTA] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ALERTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Bandeja_alertas_generadas_SOS_CODIGO_ALERTA]    Script Date: 5/8/2025 15:14:36 ******/
CREATE NONCLUSTERED INDEX [IX_Bandeja_alertas_generadas_SOS_CODIGO_ALERTA] ON [dbo].[bandeja_alertas_generadas_SOS]
(
	[CODIGO_ALERTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Bandeja_alertas_generadas_SOS_CUIL]    Script Date: 5/8/2025 15:14:36 ******/
CREATE NONCLUSTERED INDEX [IX_Bandeja_alertas_generadas_SOS_CUIL] ON [dbo].[bandeja_alertas_generadas_SOS]
(
	[CUIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Bandeja_alertas_generadas_SOS_FECHA_ALTA_ALERTA]    Script Date: 5/8/2025 15:14:36 ******/
CREATE NONCLUSTERED INDEX [IX_Bandeja_alertas_generadas_SOS_FECHA_ALTA_ALERTA] ON [dbo].[bandeja_alertas_generadas_SOS]
(
	[FECHA_ALTA_ALERTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Bandeja_alertas_generadas_SOS_FECHA_VTO_ALERTA]    Script Date: 5/8/2025 15:14:36 ******/
CREATE NONCLUSTERED INDEX [IX_Bandeja_alertas_generadas_SOS_FECHA_VTO_ALERTA] ON [dbo].[bandeja_alertas_generadas_SOS]
(
	[FECHA_VTO_ALERTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
