package ar.com.hipotecario.canal.officebanking.enums.echeq;

public enum EnumAccionesEcheqOB {
    EMISION, ENDOSO, CESION, DEPOSITO,ACEPTACION_DEVOLUCION,SOLICITAR_DEVOLUCION_EMISOR,SOLICITAR_DEVOLUCION_ENDOSANTE,ANULACION, CUSTODIAR, RESCATAR,SOLICITAR_DEVOLUCION_AVALISTA,SOLICITAR_AVAL,ADMITIR_AVAL,MANDATO_NEG, ACEPTACION_MANDATO_NEG, SOLICITAR_DEVOLUCION_MANDATARIO, REVOCATORIA_MANDATO;
}
