USE esales
GO

IF NOT EXISTS (
	SELECT * 
	FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_NAME = 'Sesion_Esales_BB2' 
	AND COLUMN_NAME = 'code_vu'
)
BEGIN
	ALTER TABLE Sesion_Esales_BB2
	ADD code_vu VARCHAR(30) NULL
END
GO
