USE esales
GO

IF EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'fecha_creacion' AND TABLE_NAME = 'SesionesStandBy')
BEGIN
  ALTER TABLE dbo.SesionesStandBy DROP COLUMN fecha_creacion
END
GO

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'score' AND TABLE_NAME = 'SesionesStandBy')
BEGIN
  ALTER TABLE [dbo].[SesionesStandBy] ADD score VARCHAR(60) NULL
END
GO

