USE esales
GO

IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'adjust_adid' AND TABLE_NAME = 'Sesion_Esales_BB2')
BEGIN
  ALTER TABLE [dbo].[Sesion_Esales_BB2] ADD adjust_adid VARCHAR(MAX) NULL
END
GO


IF NOT EXISTS (
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'adjust_gps_adid' AND TABLE_NAME = 'Sesion_Esales_BB2')
BEGIN
  ALTER TABLE [dbo].[Sesion_Esales_BB2] ADD adjust_gps_adid VARCHAR(MAX) NULL
END
GO
