package ar.com.hipotecario.backend.servicio.api.transmit;

public enum ErroresMigracionTransmitEnum {
    ERROR_CLAVE_USUARIO,
    ERROR_DATOS_BASICOS,
    ERROR_DATOS_BASICOS_MULTIPLES,
    ERROR_DATOS_BASICOS_SEXO,
    ERROR_PERSONA_NO_ENCONTRADA,
    ERROR_EMAIL_NO_ENCONTRADO,
    ERROR_TELEFONO_NO_ENCONTRADO,
    ERROR_LIBRERIA_RESPONSE_NULL,
    ERROR_LIBRERIA_RESPONSE_ERROR,
    ERROR_LIBRERIA_MAPEO_RESPONSE,
    ERROR_LIBRERIA_ACTUALIZACION_ESTADO_MIGRACION,
    ERROR_LIBRERIA_OBTENER_ESTADO_MIGRACION,
    ERROR_LIBRERIA_EMAIL_DUPLICADO
}
