package ar.com.hipotecario.backend.servicio.api.firmas;

public enum ErroresCore {
	FIRMANTE_NO_HABILITADO_EN_DICTAMEN, FUNCIONALIDAD_OB_NO_HABILITADA, PENDIENTE_BANCO, EXCEDE_EL_MONTO, ERROR_FUNCIONAL, ERROR_GENERAL, RESPUESTA_DESCONOCIDA
}