package ar.com.hipotecario.backend.util;

public class Errores {

    public static String NO_ENCUENTRA_PERSONAS = "ERROR_NO_ENCUENTRA_PERSONAS";
    public static String PERSONA_NO_ENCONTRADA = "PERSONA_NO_ENCONTRADA";
    public static String MULTIPLES_PERSONAS_ENCONTRADAS = "MULTIPLES_PERSONAS_ENCONTRADAS";
    public static String EXISTE_SESION = "EXISTE_SESION";
    public static String USUARIO_BLOQUEADO_POR_FRAUDE_LINK = "USUARIO_BLOQUEADO_POR_FRAUDE_LINK";
    public static String ERROR_GENERICO = "ERROR";
    public static String COBIS_CAIDO = "COBIS_CAIDO";
    public static String ERROR_EN_MIGRACION_LIBRERIA = "ERROR_MIGRACION_LIBRERIA";
    public static String ERROR_EN_BUSCAR_ESTADO_MIGRACION = "ERROR_BUSCAR_ESTADO_MIGRACION";
    public static String ERROR_EN_ACTUALIZAR_ESTADO_MIGRACION = "ERROR_EN_ACTUALIZAR_ESTADO_MIGRACION";
    public static String ERROR_PERSONA_NO_ENCONTRADA = "ERROR_PERSONA_NO_ENCONTRADA";
    public static String ERROR_TELEFONO_NO_ENCONTRADA = "ERROR_TELEFONO_NO_ENCONTRADA";
    public static String ERROR_EMAIL_NO_ENCONTRADA = "ERROR_EMAIL_NO_ENCONTRADA";
    public static String ERROR_LOGIN_LIBRERIA = "ERROR_LOGIN_LIBRERIA";
    public static String ERROR_DATOS_VALIDACION = "ERROR_DATOS_LIBRERIA";
    public static String USUARIO_INVALIDO = "USUARIO_INVALIDO";
    public static String ERROR_GENERACION_TOKEN = "ERROR_GENERACION_TOKEN";
    public static String EN_MANTENIMIENTO = "EN_MANTENIMIENTO";
    public static String ERROR_MIGRAR_TRADICIONAL = "ERROR_MIGRAR_TRADICIONAL";
    public static String ERROR_USUARIO_NO_MIGRADO = "ERROR_USUARIO_NO_MIGRADO";
    public static String ERROR_MIGRACION_COMPLETA = "ERROR_MIGRACION_COMPLETA";
    public static String ERROR_CLAVE_REPETIDA = "ERROR_CLAVE_REPETIDA";
    public static String ERROR_CAMBIO_CLAVE = "ERROR_CAMBIO_CLAVE";
    public static String ERROR_USUARIO_REPETIDO = "ERROR_USUARIO_REPETIDO";
    public static String ERROR_CAMBIO_USUARIO = "ERROR_CAMBIO_USUARIO";
    public static String FUNCIONALIDAD_APAGADA = "FUNCIONALIDAD_APAGADA";
    public static String ERROR_USUARIO_NO_MIGRADO_MULTIPLES = "ERROR_USUARIO_NO_MIGRADO_MULTIPLES";

}
